package noniljson

import (
	"go/ast"
	"go/types"
	"strings"
)

// Linter configs
var ignoreGeneratedFiles bool

// isNullableType checks if the given type is considered nullable for JSON purposes.
func isNullableType(typ types.Type) bool {
	switch typ.Underlying().(type) {
	case *types.Pointer, *types.Slice, *types.Map, *types.Interface:
		return true
	default:
		return false
	}
}

// isGeneratedFile checks if the given file is generated by tools like go generate.
func isGeneratedFile(comments []*ast.CommentGroup) bool {
	for _, cg := range comments {
		for _, comment := range cg.List {
			if strings.HasPrefix(comment.Text, "// Code generated") {
				return true
			}
		}
	}
	return false
}
